server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Cabeceras de seguridad
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' https://static-content-qas.vnforapps.com https://static-content.secure.niubiz.com.pe; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https: data:; connect-src 'self' https://hotelsanfranciscobackend-production.up.railway.app wss://hotelsanfranciscobackend-production.up.railway.app https://fonts.googleapis.com https://fonts.gstatic.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; object-src 'none'" always;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
